version: "2.0"
services:
  # Load Balancer (NginX)
  wetbat_lb:
    container_name: "wetbat-lb"
    image: wetbat-lb:latest
    restart: always
    volumes:
      - "./load-balancer/certs:/etc/letsencrypt"
    depends_on:
      - "wetbat_portal"
    links:
      - "wetbat_portal:wetbat_portal"
    build:
      context: ./load-balancer/
    ports:
      - "80:80"
      - "443:443"
  # Database (MySQL)
  wetbat_db:
    container_name: "wetbat-db"
    image: wetbat-db:latest
    build:
      context: ./database/
    volumes:
      - "./database/data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
  # Main API / Portal for wetbat (React / Express)
  wetbat_portal:
    container_name: "wetbat-portal"
    image: wetbat:latest
    restart: always
    build:
      context: ./server/
    depends_on:
      - "wetbat_db"
    links:
      - "wetbat_db:wetbat_db"
    volumes:
      - "./server/build:/opt/wetbat/build"
      - "./server/node_modules:/opt/wetbat/node_modules"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      API_HOST: ${API_HOST_DOCKER}
      API_VERSION: ${API_VERSION}
      API_ROUTE_PATH: ${API_ROUTE_PATH}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST_DOCKER}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      PUBLIC_URL: ${PUBLIC_URL}
      ENABLE_AUTH: ${ENABLE_AUTH}
